### ISSUE TITLE
Add file copying

### ISSUE THREAD

**Issue by ninjalandia** [ninjalandia/CodespaceMPT#32]
When the user makes a command like `githubfile ninjalandia CodespaceMPT docs/api/index.html` the contents of that file get copied to clipboard and then the user can edit the file in our code box.

**Comment by ninjalandia** [comment]
@ArgentiCityZenx

**Comment by ArgentiCityZenx** [comment]
I Like it

**Comment by ninjalandia** [comment]
yay!!!
